openapi: 3.1.0
info:
  title: Planarific Dwelling Typology API
  description: |
    This API defines the endpoints made available by the Planarific system for the retrieval of the typology matching and associated data of one or more dwellings. The API is RESTful. Users of the API can complete the following actions: 

    - Submit one UPRN to identify dwellings for which information is to be retrieved. 

    - Receive back for the UPRN submitted the typology matching data for the dwelling. 

    - Receive back for the UPRN submitted the building measurement and feature data for the dwelling. 

  contact:
    email: ant.skelton@planarific.com
  version: 1.0.0
  license:
    name: unlicensed
    url: https://www.planarific.com

tags:
  - name: typology
    description: This group of endpoints provides operations for typology assessment of dwellings.

security:
  - clientCredentials:
    - read:typology

servers:
  - url: https://planarific.dev
  - url: https://planarific.app

paths:
  /api/v1/typology/dwellings/{country_code}/{uprn}:
    get:
      summary: Typology data
      description: |
        This endpoint returns typology data for a single dwelling
        given its UPRN. This data will include the dwelling type,
        roof type, number of storeys and number of party walls.

        It may additionally include extended information such as
        the orientation of the entrance, whether there is a shared
        porch, the footprint area, bulding height, roof surface area,
        building volume, boundary road and side passage distances,
        drainage, overhead cables and garden access information.

      tags:
        - typology
      operationId: getDwelling
      parameters:
        - name: country_code
          in: path
          description: ISO3166-1 alpha-2 country code.
          required: true
          schema:
            type: string
            format: string
        - name: uprn
          in: path
          description: Unique Property Reference Number
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: Typology matching data for the given UPRN.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dwellingDataResponse'
              examples:
                one:
                  $ref: '#/components/examples/dwellingExample'
        '404':
          description: UPRN not found
  /api/v1/typology/dwellings/{country_code}/{uprn}/matches:
    get:
      summary: Matching UPRNs
      description: |
        This endpoint returns an array of property UPRNs
        that most closely match the provided UPRN according to the
        aggregate of two different similarity metrics.

        The results may be paginated, as indicated by the `offset`,
        `limit`, `total` and `final` properties. 

      tags:
        - typology
      operationId: getMatches
      parameters:
        - name: country_code
          in: path
          description: ISO3166-1 alpha-2 country code.
          required: true
          schema:
            type: string
            format: string
        - name: uprn
          in: path
          description: Unique Property Reference Number
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: Matching properties for the given UPRN.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/matchingPropertiesRecord'
              examples:
                one:
                  $ref: '#/components/examples/matchExample'
        '404':
          description: UPRN not found
  /api/v1/typology/dwellings/{country_code}/{uprn}/features:
    get:
      summary: Get Features for UPRN
      description: |
        This endpoint returns a list of property features
        that match the provided UPRN.

      tags:
        - typology
      operationId: getFeatures
      parameters:
        - name: country_code
          in: path
          description: ISO3166-1 alpha-2 country code.
          required: true
          schema:
            type: string
            format: string
        - name: uprn
          in: path
          description: Unique Property Reference Number
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: Property features for the given UPRN.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/featureListRecord'
              examples:
                one:
                  $ref: '#/components/examples/featuresExample'
        '404':
          description: UPRN not found
  /api/v1/typology/dwellings/{country_code}/{uprn}/features/{featureId}:
    get:
      summary: Get Feature detail
      description: |
        This endpoint returns detailed feature information
        for the given UPRN and Feature ID.

      tags:
        - typology
      operationId: getFeature
      parameters:
        - name: country_code
          in: path
          description: ISO3166-1 alpha-2 country code.
          required: true
          schema:
            type: string
            format: string
        - name: uprn
          in: path
          description: Unique Property Reference Number
          required: true
          schema:
            type: string
            format: string
        - name: featureId
          in: path
          description: Unique feature ID
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: Property feature detailed information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/featureRecord'
              examples:
                one:
                  $ref: '#/components/examples/featureExample'
        '404':
          description: UPRN or featureId not found
  /api/v1/typology/dwellings/{country_code}/{uprn}/parts:
    get:
      summary: Get Building Parts for UPRN
      description: |
        This endpoint returns a list of building parts
        that match the provided UPRN.

      tags:
        - typology
      operationId: getBuildingParts
      parameters:
        - name: country_code
          in: path
          description: ISO3166-1 alpha-2 country code.
          required: true
          schema:
            type: string
            format: string
        - name: uprn
          in: path
          description: Unique Property Reference Number
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: Building Parts for the given UPRN.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/partsListRecord'
              examples:
                one:
                  $ref: '#/components/examples/partsExample'
        '404':
          description: UPRN not found
  /api/v1/typology/dwellings/{country_code}/{uprn}/parts/{partId}:
    get:
      summary: Get Building Part detail
      description: |
        This endpoint returns detailed building part information
        for the given UPRN and Building Part ID.

      tags:
        - typology
      operationId: getPart
      parameters:
        - name: country_code
          in: path
          description: ISO3166-1 alpha-2 country code.
          required: true
          schema:
            type: string
            format: string
        - name: uprn
          in: path
          description: Unique Property Reference Number
          required: true
          schema:
            type: string
            format: string
        - name: partId
          in: path
          description: Unique building part ID
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: Building Part detailed information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/partRecord'
              examples:
                one:
                  $ref: '#/components/examples/partExample'
        '404':
          description: UPRN or partId not found

components:
  securitySchemes:
    clientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.planarific.dev/token
          scopes:
            read:typology: Read typology information
  schemas:
    dwellingType:
      type: string
      enum:
        - Detached
        - Semi-detached
        - Mid-terrace
        - End-terrace
        - Bungalow
        - Flat
    roofType:
      type: string
      enum:
        - Gable to gable
        - Gable to hip
        - Hip to hip
        - L-shaped gable
        - L-shaped hip
        - L-shaped gable to hip
        - Flat
        - Ultra-low pitch
    featureType:
      type: string
      enum:
        - Cable connection
        - Chimney
        - Circular air vent
        - Conservatory
        - Decorative feature
        - Disabled accessory
        - Down pipe
        - Drive way
        - Flue
        - Gas meter
        - Ginnel
        - Key safe
        - Lean-to
        - Letter box
        - Lintel
        - Porch
        - Satellite dish
        - Side gate
        - Solar panel
        - Wimpey corbel
        - Wimpey low-level brick
        - Wimpey porch
        - Wimpey tiled sill
        - Window trickle vent
    partType:
      type: string
      enum:
        - Wall
        - Roof slope
        - Window (standard)
        - Window (dormer)
        - Window (bay)
        - Window (bow)
        - Door
        - Extension
    finishType:
      type: string
      enum:
        - Brick (stretcher)
        - Brick (Flemish)
        - Brick (English)
        - Brick (unknown)
        - Render
        - Pebbledash
        - Tile (slate)
        - Tile (concrete)
        - Tile (unknown)
        - Thatch
    entranceOrientationType:
      type: string
      enum:
        - Street
        - Side
    dwellingDataResponse:
      type: object
      properties:
        uprn:
          type: string
        dwelling_data:
          $ref: '#/components/schemas/dwellingDataRecord'

    dwellingDataRecord:
      type: object
      required:
        - dwelling_type
        - roof_type
        - number_of_storeys
        - number_of_party_walls
      properties:
        dwelling_type:
          $ref: '#/components/schemas/dwellingType'
        roof_type:
          $ref: '#/components/schemas/roofType'
        number_of_storeys:
          type: number
        number_of_party_walls:
          type: number
        entrance_orientation:
          $ref: '#/components/schemas/entranceOrientationType'
        shared_porch:
          type: boolean
        footprint_area:
          description: Area of the footprint of the building (m^2)
          type: number
        height:
          description: Building height from ground to gutter (m)
          type: number
        roof_surface_area:
          description: Surface area of the roofs of a building (m^2)
          type: number
        volume:
          description: Total volume of the building (m^3)
          type: number
        boundary_distance_front:
          description: Distance from the front wall to the plot boundary (m)
          type: number
        boundary_distance_side:
          description: Distance from the side walls to the plot boundary (m)
          type: number
        road_distance:
          description: Is the property less than 5m from the road?
          type: boolean
        side_passage_width:
          description: Width of passages alongside the property (m)
          type: number
        drainage_by_wall:
          description: Does the property have manholes or gulleys by the wall?
          type: boolean
        low_hanging_cables:
          description: Are there low-hanging cables within 2m of the property?
          type: boolean
        garden_access:
          description: Is there access to the back garden without going into the property?
          type: boolean
        garden_space:
          description: Is there more than 3m by 3m of clear space in the back garden?
          type: boolean
        
    matchingPropertiesRecord:
      type: object
      required:
        - offset
        - limit
        - total
        - final
        - items
      properties:
        offset:
          type: integer
        limit:
          type: integer
        total:
          type: integer
        final:
          type: boolean
        items:
          type: array
          items:
            type: object
            properties:
              matching_uprn:
                type: string
              similarity_index_rank_a:
                type: integer
                description: |
                  The rank index that represents how similar the property is to the queried property based on 
                  typology clustering logic from model A, where a rank of 1 indicates the most similarity.

              similarity_index_rank_b:
                type: integer
                description: |
                  The rank index that represents how similar the property is to the queried property based on 
                  typology clustering logic from model A, where a rank of 1 indicates the most similarity.

    featureListRecord:
      type: object
      required:
        - offset
        - limit
        - total
        - final
        - items
      properties:
        offset:
          type: integer
        limit:
          type: integer
        total:
          type: integer
        final:
          type: boolean
        items:
          type: array
          items:
            type: object
            required:
              - name
              - id
            properties:
              name:
                description: Name of feature
                type: string
              id:
                description: Unique feature ID of feature
                type: string
      
    featureRecord:
      type: object
      required:
        - id
        - name
        - type
        - count
      properties:
        id:
          description: Unique ID for feature
          type: string
        name:
          description: Descriptive label for this feature
          type: string
        type:
          $ref: '#/components/schemas/featureType'
        count:
          type: number

    partsListRecord:
      type: object
      required:
        - offset
        - limit
        - total
        - final
        - items
      properties:
        offset:
          type: integer
        limit:
          type: integer
        total:
          type: integer
        final:
          type: boolean
        items:
          type: array
          items:
            type: object
            required:
              - name
              - id
            properties:
              name:
                description: Name of building part
                type: string
              id:
                description: UNique ID of building part
                type: string

    partRecord:
      type: object
      required:
        - id
        - name
        - type
      properties:
        id:
          description: Unique ID for building part
          type: string
        name:
          description: Descriptive label for the building part
          type: string
        type:
          description: Building part type
          $ref: '#/components/schemas/partType'
        height:
          description: Height of the building part (mm)
          type: number
        width:
          description: Width of the building part (mm)
          type: number
        depth:
          description: Depth of the building part (mm)
          type: number
        area:
          description: Surface area of the building part (mm^2)
          type: number
        volume:
          description: Volume of the building part (mm^3)
          type: number
        angle:
          description: |
            Angle of the plane of the building part to
            the ground in degrees (roofs only).

          type: number
        azimuth:
          description: |
            Angle of the horizontal direction in which the roof
            faces, measured clockwise from North in degrees (roofs only).

          type: number
        finish_type:
          description: Finish type of the surface of the building part
          $ref: '#/components/schemas/finishType'
        dpc_height:
          description: Height above the ground of the damp proof course (mm)
          type: number
        dpc_area_above:
          description: |
            Surface area of the part above the damp proof course (mm)
            - walls only.

          type: number
        dpc_area_below:
          description: |
            Surface area of the part below the damp proof course (mm)
            - walls only.

          type: number
        soffit_depth:
          description: Depth of the soffit (mm) - roofs only
          type: number

  examples:
    dwellingExample:
      summary: Example dwelling data record
      value:
        uprn: "100062410143"
        dwelling_data:
          dwelling_type: Detached
          roof_type: Flat
          number_of_storeys: 2
          number_of_party_walls: 0
          entrance_orientation: Street
          shared_porch: false
          footprint_area: 150
          height: 9
          roof_surface_area: 60
          volume: 1000
          boundary_distance_front: 2
          boundary_distance_side: 1
          road_distance: false
          side_passage_width: 0
          drainage_by_wall: false
          low_hanging_cables: false
          garden_access: true
          garden_space: true

    matchExample:
      summary: Example UPRN property match record
      value:
        offset: 0
        limit: 2
        total: 2
        final: true
        items:
          - matching_uprn: "100062410143"
            similarity_index_rank_a: 1
            similarity_index_rank_b: 1
          - matching_uprn: "100062410144"
            similarity_index_rank_a: 2
            similarity_index_rank_b: 2

    featuresExample:
      summary: Example building features list record
      value:
        offset: 0
        limit: 2
        total: 2
        final: true
        items:
          - name: Chimney42
            id: "1234567890"
          - name: Man hole cover 99
            id: "1234567809"

    featureExample:
      summary: Example building feature record
      value:
        id: "1234567890"
        name: Chimney42
        type: Chimney
        count: 1

    partsExample:
      summary: Example building parts list record
      value:
        offset: 0
        limit: 2
        total: 2
        final: true
        items:
          - id: "1234567890"
            name: Wall42
          - id: "2143658709"
            name: Roof1

    partExample:
      summary: Example building part record
      value:
        id: "1234567890"
        name: Wall42
        type: Wall
        height: 2400
        width: 9000
        depth: 150
        area: 2000
        volume: 3000
        finish_type: Brick (stretcher)
        dpc_height: 150
        dpc_area_above: 2000
        dpc_area_below: 1000
        soffit_depth: 200
        
